---
- name: MinIO LFS Server Setup with Tailscale and HTTPS
  hosts: minio_servers
  become: yes
  gather_facts: yes
  
  vars:
    minio_user: minio
    minio_uid: 1001
    minio_gid: 1001
    minio_data_path: /mnt/external-ssd/minio-data
    minio_config_path: /mnt/external-ssd/minio-config
    minio_certs_path: /mnt/external-ssd/minio-certs
    minio_root_user: gitlab-lfs-admin
    minio_root_password: SuperSecurePassword123!
    gitlab_lfs_user: gitlab-lfs-user
    gitlab_lfs_password: GitLabLFS2025!
    lfs_bucket_name: mfc-project-lfs
    tailscale_auth_key: "{{ vault_tailscale_auth_key }}"  # Store in Ansible Vault
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - curl
          - wget
          - gnupg
          - lsb-release
          - ca-certificates
          - htop
          - ncdu
          - tree
          - vim
          - fuse3
          - jq
          - ufw
        state: present

    - name: Create mount point for external SSD
      file:
        path: /mnt/external-ssd
        state: directory
        mode: '0755'

    - name: Mount external SSD via virtiofs
      mount:
        path: /mnt/external-ssd
        src: external-ssd
        fstype: virtiofs
        opts: defaults
        state: mounted

    - name: Add virtiofs mount to fstab
      mount:
        path: /mnt/external-ssd
        src: external-ssd
        fstype: virtiofs
        opts: defaults
        state: present

    - name: Create minio group
      group:
        name: "{{ minio_user }}"
        gid: "{{ minio_gid }}"
        state: present

    - name: Create minio user
      user:
        name: "{{ minio_user }}"
        uid: "{{ minio_uid }}"
        group: "{{ minio_user }}"
        shell: /bin/false
        home: "{{ minio_data_path }}"
        create_home: no
        system: yes
        state: present

    - name: Create MinIO directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ minio_user }}"
        group: "{{ minio_user }}"
        mode: '0755'
      loop:
        - "{{ minio_data_path }}"
        - "{{ minio_config_path }}"
        - "{{ minio_certs_path }}"

    # Docker Installation
    - name: Remove old Docker packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ansible user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Tailscale Installation
    - name: Add Tailscale GPG key
      get_url:
        url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main"
        state: present
        update_cache: yes

    - name: Install Tailscale
      apt:
        name: tailscale
        state: present

    - name: Start Tailscale
      command: tailscale up --accept-routes --accept-dns --advertise-tags=tag:minio-server --authkey={{ tailscale_auth_key }}
      register: tailscale_result
      changed_when: "'Success' in tailscale_result.stdout"

    - name: Get Tailscale hostname
      command: tailscale status --json
      register: tailscale_status
      changed_when: false

    - name: Set Tailscale hostname fact
      set_fact:
        tailscale_hostname: "{{ (tailscale_status.stdout | from_json).Self.DNSName | regex_replace('\\.$', '') }}"

    - name: Request Let's Encrypt certificate via Tailscale
      command: tailscale cert --domain {{ tailscale_hostname }}
      register: cert_result
      changed_when: "'Success' in cert_result.stdout or cert_result.rc == 0"

    - name: Copy Tailscale certificates for MinIO
      copy:
        src: "/var/lib/tailscale/certs/{{ tailscale_hostname }}.{{ item.ext }}"
        dest: "{{ minio_certs_path }}/{{ item.dest }}"
        owner: "{{ minio_user }}"
        group: "{{ minio_user }}"
        mode: "{{ item.mode }}"
        remote_src: yes
      loop:
        - { ext: "crt", dest: "public.crt", mode: "0644" }
        - { ext: "key", dest: "private.key", mode: "0600" }

    # MinIO Client Installation
    - name: Download MinIO client
      get_url:
        url: https://dl.min.io/client/mc/release/linux-amd64/mc
        dest: /usr/local/bin/mc
        mode: '0755'
        owner: root
        group: root

    # MinIO Docker Compose Setup
    - name: Create MinIO setup directory
      file:
        path: /home/{{ ansible_user }}/minio-setup
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create docker-compose.yml for MinIO
      template:
        src: docker-compose.yml.j2
        dest: /home/{{ ansible_user }}/minio-setup/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Start MinIO with Docker Compose
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/minio-setup
        state: present
      become_user: "{{ ansible_user }}"

    - name: Wait for MinIO to be ready
      uri:
        url: "https://{{ tailscale_hostname }}:9000/minio/health/live"
        validate_certs: no
        timeout: 10
      register: minio_health
      until: minio_health.status == 200
      retries: 12
      delay: 10

    # MinIO Configuration
    - name: Configure MinIO client alias
      command: mc alias set minio-secure https://{{ tailscale_hostname }}:9000 {{ minio_root_user }} {{ minio_root_password }}
      become_user: "{{ ansible_user }}"
      register: mc_alias_result
      changed_when: "'Added' in mc_alias_result.stdout"

    - name: Create GitLab LFS user
      command: mc admin user add minio-secure {{ gitlab_lfs_user }} {{ gitlab_lfs_password }}
      become_user: "{{ ansible_user }}"
      register: lfs_user_result
      changed_when: "'Added user' in lfs_user_result.stdout"
      failed_when: lfs_user_result.rc != 0 and 'already exists' not in lfs_user_result.stderr

    - name: Create LFS policy file
      copy:
        content: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:DeleteObject",
                  "s3:ListBucket",
                  "s3:GetObjectVersion",
                  "s3:GetBucketLocation"
                ],
                "Resource": [
                  "arn:aws:s3:::{{ lfs_bucket_name }}",
                  "arn:aws:s3:::{{ lfs_bucket_name }}/*"
                ]
              }
            ]
          }
        dest: /home/{{ ansible_user }}/lfs-policy.json
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Create LFS policy in MinIO
      command: mc admin policy create minio-secure lfs-policy /home/{{ ansible_user }}/lfs-policy.json
      become_user: "{{ ansible_user }}"
      register: policy_result
      changed_when: "'Policy' in policy_result.stdout"
      failed_when: policy_result.rc != 0 and 'already exists' not in policy_result.stderr

    - name: Attach policy to LFS user
      command: mc admin policy attach minio-secure lfs-policy --user {{ gitlab_lfs_user }}
      become_user: "{{ ansible_user }}"
      register: attach_result
      changed_when: attach_result.rc == 0

    - name: Create LFS bucket
      command: mc mb minio-secure/{{ lfs_bucket_name }}
      become_user: "{{ ansible_user }}"
      register: bucket_result
      changed_when: "'Bucket created' in bucket_result.stdout"
      failed_when: bucket_result.rc != 0 and 'already exists' not in bucket_result.stderr

    - name: Enable versioning on LFS bucket
      command: mc version enable minio-secure/{{ lfs_bucket_name }}
      become_user: "{{ ansible_user }}"
      register: version_result
      changed_when: version_result.rc == 0

    # Security Configuration
    - name: Configure UFW default policies
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Allow SSH through firewall
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Tailscale interface
      ufw:
        rule: allow
        interface: tailscale0
        direction: in

    - name: Allow MinIO ports from Tailscale
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        port: "{{ item }}"
        comment: "MinIO {{ item == '9000' and 'API' or 'Console' }} via Tailscale"
      loop:
        - "9000"
        - "9001"

    - name: Enable UFW
      ufw:
        state: enabled

    # Maintenance Scripts
    - name: Create certificate update script
      template:
        src: update-minio-certs.sh.j2
        dest: /home/{{ ansible_user }}/update-minio-certs.sh
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create health check script
      template:
        src: minio-health-check.sh.j2
        dest: /home/{{ ansible_user }}/minio-health-check.sh
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create backup script
      template:
        src: backup-minio-config.sh.j2
        dest: /home/{{ ansible_user }}/backup-minio-config.sh
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Setup cron jobs
      cron:
        name: "{{ item.name }}"
        cron_file: minio-maintenance
        user: "{{ ansible_user }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        day: "{{ item.day | default('*') }}"
        weekday: "{{ item.weekday | default('*') }}"
        job: "{{ item.job }}"
      loop:
        - name: "MinIO certificate renewal"
          minute: "0"
          hour: "2"
          weekday: "0"
          job: "/home/{{ ansible_user }}/update-minio-certs.sh >> /var/log/minio-cert-update.log 2>&1"
        - name: "MinIO health check"
          minute: "0"
          hour: "*"
          job: "/home/{{ ansible_user }}/minio-health-check.sh >> /var/log/minio-health.log 2>&1"
        - name: "MinIO configuration backup"
          minute: "0"
          hour: "3"
          job: "/home/{{ ansible_user }}/backup-minio-config.sh >> /var/log/minio-backup.log 2>&1"

    - name: Create log rotation configuration
      copy:
        content: |
          /var/log/minio-*.log {
            daily
            rotate 30
            compress
            delaycompress
            missingok
            notifempty
            create 0644 {{ ansible_user }} {{ ansible_user }}
          }
        dest: /etc/logrotate.d/minio
        mode: '0644'

  handlers:
    - name: restart docker
      systemd:
        name: docker
        state: restarted